Given the dynamic system with recurrence relationship si = s^2
i-1 +c, compute the value of s, given that = 0.6471136 and c= - 1- Report the
solutions to at least two decimal places.

In [31]:
s = 0.7391
c = -1

# Compute s_5 using the recurrence relation
for i in range(5):
    print(i)
    print(s)
    s = s**2 + c

print("Value of s_5:", s)

0
0.7391
1
-0.45373119000000006
2
-0.7941280072211838
3
-0.36936070814691147
4
-0.8635726672772122
Value of s_5: -0.2542422483317214


Perform max pooling on the matrix A, using a 2x 2 kernel with stride of 2, to obtain a 2x2 matrix. What is the trace of the resulting 2x2 matrix?

In [14]:
A = np.array([[-10, 9, 7, 3], 
              [10, 2, -4, 3], 
              [-10, -4, 0, 10],
             [-3, 5, 4, -2]])

# Reshape A to make it easier for max pooling in this specific case
A_reshaped = A.reshape((2, 2, 2, 2))
print(A)
# Perform max pooling
max_pooled = np.max(A_reshaped, axis=(1, 3))

# Trace of the resulting max pooled matrix
trace_max_pooled = np.trace(max_pooled)
print("Max pooled matrix:", max_pooled)
print("Trace of the max pooled matrix:", trace_max_pooled)

[[-10   9   7   3]
 [ 10   2  -4   3]
 [-10  -4   0  10]
 [ -3   5   4  -2]]
Max pooled matrix: [[10  7]
 [ 5 10]]
Trace of the max pooled matrix: 20


An LSTM unit (as shown in the Recurrent Networks lecture) contains a set of gates that switch on and off components of the input, hidden state feedback, and output.
One of the gates has weight matrices: 
U = np.array([[1, 0], [0, 1]])
V = np.array([[0, 1], [1, 0]])
b = np.array([0, 0])
Compute the gate output when the two element input is x = [1.6261812 12.9230591) and the previous hidden state is
1"-1)=(-0.4635565 0.3054632). Using the two element output vector, report the first element. Report the solutions to at least two decimal places.

In [27]:
import numpy as np

# Define matrices and vectors
U = np.array([[1, 0], [0, 1]])
V = np.array([[0, 1], [1, 0]])
b = np.array([0, 0])
x = np.array([6.8864025, 5.5391765])
h_prev = np.array([-0.0619117, -0.3059627])

# Compute Ux, Vh_prev, and h_t
Ux = np.dot(U, x)
Vh_prev = np.dot(V, h_prev)
h_t = np.tanh(Ux + Vh_prev + b)

print("Ux:", Ux)
print("Vh_prev:", Vh_prev)
print("Output h_t:", h_t)

Ux: [6.8864025 5.5391765]
Vh_prev: [-0.3059627 -0.0619117]
Output h_t: [0.99999615 0.99996504]


In [25]:
import numpy as np
import math

# Define the weight matrices, bias vector, input, and previous hidden state
U = np.array([[1, 0], [0, 1]])
V = np.array([[0, 1], [1, 0]])
b = np.array([0, 0])
x = np.array([6.8864025, 5.5391765])
h_prev = np.array([-0.0619117, -0.3059627])

# Sigmoid function
def sigmoid(z):
    return 1 / (1 + np.exp(-z))

# Compute the gate output: g = sigmoid(Ux + Vh_prev + b)
gate_output = sigmoid(np.dot(U, x) + np.dot(V, h_prev) + b)

# First element of the output
first_element = gate_output[0]
print(round(first_element,2))

1.0


In [26]:
import numpy as np

# Define the matrices and vectors
U = np.array([[1, 0], [0, 1]])
V = np.array([[0, 1], [1, 0]])
b = np.array([0, 0])
x = np.array([6.8864025, 5.5391765])
h_t_minus_1 = np.array([-0.0619117, -0.3059627])

# Sigmoid function
def sigmoid(z):
    return 1 / (1 + np.exp(-z))

# Perform the matrix multiplications
Ux = np.dot(U, x)
Vh_t_minus_1 = np.dot(V, h_t_minus_1)

# Add the components: Ux + Vh + b
result = Ux + Vh_t_minus_1 + b

# Apply the sigmoid function
output = sigmoid(result)

# Return the first element of the output
print("First element of the output:", output[0])
print("Full output vector:", output)

First element of the output: 0.9986146827133227
Full output vector: [0.99861468 0.99583666]


Compute the unflipped convolution of A and B. giving a 2x 2 matrix. What is the trace of the resulting 2x 2 matrix?

In [16]:
A = np.array([[-1, -7, 10], [-2, 2, 2], [3, -5, 0]])
B = np.array([[-2, -3], [8, -4]])

# Function to perform convolution
def convolution2d(A, B):
    # Get the dimensions for the output matrix
    output_dim = (A.shape[0] - B.shape[0] + 1, A.shape[1] - B.shape[1] + 1)
    # Initialize the output matrix with zeros
    output = np.zeros(output_dim)
    
    # Perform element-wise multiplication and summing
    for i in range(output_dim[0]):
        for j in range(output_dim[1]):
            output[i, j] = np.sum(A[i:i+B.shape[0], j:j+B.shape[1]] * B)
    
    return output

# Perform convolution
result_matrix = convolution2d(A, B)
print(A)
print(B)
# Compute trace of the resulting matrix
trace_result = np.trace(result_matrix)

print("Resulting matrix from convolution:", result_matrix)
print("Trace of the resulting matrix:", trace_result)

[[-1 -7 10]
 [-2  2  2]
 [ 3 -5  0]]
[[-2 -3]
 [ 8 -4]]
Resulting matrix from convolution: [[ -1.  -8.]
 [ 42. -50.]]
Trace of the resulting matrix: -51.0


In [17]:
import numpy as np

# Define matrices A and B
A = np.array([[-1, -7, 10], [-2, 2, 2], [3, -5, 0]])
B = np.array([[-2, -3], [8, -4]])

# Perform unflipped convolution (without flipping B)
# The result will be a 2x2 matrix, applying B on each 2x2 region of A
convolution_result = np.array([
    [np.sum(A[0:2, 0:2] * B), np.sum(A[0:2, 1:3] * B)],
    [np.sum(A[1:3, 0:2] * B), np.sum(A[1:3, 1:3] * B)]
])

# Compute the trace of the resulting 2x2 matrix
trace_convolution = np.trace(convolution_result)

# Print the convolution result and the trace
print("Convolution Result:\n", convolution_result)
print("Trace of the resulting matrix:", trace_convolution)

Convolution Result:
 [[ -1  -8]
 [ 42 -50]]
Trace of the resulting matrix: -51
