In [1]:
import numpy as np

In [4]:
a = np.array([[31, 75, 29], [3, 4, 21], [31, 57, 14]])
b = np.array([[33, 44, 11], [16, 4, 96], [13, 72, 13]])
print(a)
print(b)
a.dot(b)

[[31 75 29]
 [ 3  4 21]
 [31 57 14]]
[[33 44 11]
 [16  4 96]
 [13 72 13]]


array([[2600, 3752, 7918],
       [ 436, 1660,  690],
       [2117, 2600, 5995]])

In [6]:
aa = np.array([[95,26,32],[49,51,97],[29,50,64]])
a_inv = np.linalg.pinv(aa)
a_inv.dot(aa)

array([[ 1.00000000e+00,  5.06539255e-16,  4.99600361e-16],
       [-6.24500451e-17,  1.00000000e+00,  0.00000000e+00],
       [ 2.77555756e-17, -6.10622664e-16,  1.00000000e+00]])

In [7]:
aaa = np.array([[32,74,21],[77,31,99],[53,41,57]])
np.linalg.det(aaa)

21941.99999999999