In [1]:
import sklearn
import sklearn.datasets
import numpy as np
import matplotlib.pyplot as plt

In [21]:
#generate training data
x1 = np.random.multivariate_normal(mean = [1,1], cov = [[1,0], [0,1]], size = 100)
x2 = np.random.multivariate_normal(mean = [3,1], cov = [[1,0], [0,1]], size = 100)
x3 = np.random.multivariate_normal(mean = [2,2], cov = [[1,0], [0,1]], size = 100)

In [23]:
X = np.vstack([x1, x2, x3])

In [25]:
X

array([[ 9.34915064e-01, -6.85593539e-01],
       [ 3.71034518e-02,  2.27292291e+00],
       [ 5.20938477e-03,  1.28785094e-01],
       [ 3.02512556e-01,  2.80162641e+00],
       [-3.73652897e-02,  1.26559243e+00],
       [ 3.07171312e+00,  1.12651910e+00],
       [ 8.49558342e-01,  4.26587911e-02],
       [-2.42457529e-01,  1.71993907e+00],
       [-8.56336447e-02, -2.07807093e-01],
       [ 1.42692035e+00,  7.22765812e-01],
       [ 2.95769067e+00,  1.29835112e+00],
       [ 1.08978251e+00,  1.49713851e-01],
       [ 8.57221364e-01, -8.15843032e-01],
       [ 1.31145614e+00,  4.46664846e-01],
       [ 2.83630871e+00, -9.46145334e-01],
       [ 1.97435779e+00,  1.04616580e+00],
       [ 7.17480283e-01,  1.37408111e+00],
       [ 1.89594211e+00,  5.80832484e-01],
       [ 3.40449020e-01,  9.84728747e-01],
       [ 2.24201672e-01,  1.24747730e+00],
       [ 1.99384607e+00,  5.58970829e-01],
       [ 9.37190581e-01,  5.55914990e-01],
       [ 1.49144834e-01,  1.60412703e+00],
       [ 1.

In [27]:
np.repeat(0,200) # repeat 0 200 times

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [29]:
y = np.concatenate([np.repeat(0, 200), np.repeat(1, 100)])
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [35]:
plt.scatter(X[:, 0], X[:, 1], marker='o', c=y, s=25, edgecolor='k')
plt.show()

In [37]:
## generate testing data, using the same distribution as the training data
x1 = np.random.multivariate_normal(mean = [1,1], cov = [[1,0], [0,1]], size = 100)
x2 = np.random.multivariate_normal(mean = [3,1], cov = [[1,0], [0,1]], size = 100)
x3 = np.random.multivariate_normal(mean = [2,2], cov = [[1,0], [0,1]], size = 100)

In [43]:
Xtest = np.vstack([x1, x2, x3])
ytest = np.concatenate([np.repeat(0,200), np.repeat(1,100)])

##polynomial kernel

k(x i,x j)=(x i^⊤,x j+o)^d

## Regularization involves controlling model complexity to prevent overfitting.
## C regulates the balance between margin size and classification error.
## degree specifies the polynomial degree in the kernel function, affecting model complexity.
## coef0 adjusts the influence of the constant term in polynomial and sigmoid kernels.

In [48]:
# We set the hyper-parameters C to 1, coef0 to 1, and degree to 1.
from sklearn import svm
m = svm.SVC(kernel='poly', C=1, degree=1, coef0 = 1)
m.fit(X, y)

SVC(C=1, coef0=1, degree=1, kernel='poly')

In [50]:
#training accuracy
m.score(X, y)

0.7166666666666667

In [52]:
#test accuracy
m.score(Xtest, ytest)

0.6933333333333334

In [56]:
# adjust c and d to examine the effect on training and testing accuracy
c = 2
d = 3
m = svm.SVC(kernel='poly', C=c, degree=d, coef0=1)
m.fit(X,y)
print("C=", c, ", degree=", d, ", Training:", m.score(X,y), ", Testing:", m.score(Xtest, ytest))

C= 2 , degree= 3 , Training: 0.7733333333333333 , Testing: 0.7433333333333333
