In [44]:
import numpy as np
from sklearn import datasets

In [46]:
iris = datasets.load_iris()
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [48]:
X = iris.data
y = iris.target

In [50]:
# N is the sample size
# Di is the number of input features
[N, Di] = X.shape

In [52]:
# Do is the number of output features
# H1 is the number of units in the hidden layer
Do = 3
H1 = 10

In [54]:
alpha = 0.00001 # set the learning rate for gradient descent

In [56]:
y.shape

(150,)

In [58]:
y = np.reshape(y, (N,1))   # convert y to vector
y.shape

(150, 1)

In [60]:
## convert the set of categories in y to a set of one hot variables
## technique used to convert categorical variables into a numerical format
from sklearn.preprocessing import OneHotEncoder
onehot_encoder = OneHotEncoder(sparse=False)
y = onehot_encoder.fit_transform(y)

/Users/pramodkc/anaconda3/lib/python3.11/site-packages/sklearn/preprocessing/_encoders.py:972: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


In [62]:
y

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [74]:
# we are creating two layer networks so weights are needed from input to hidden and hidden to output
np.random.seed(1)
# Randomly initialize weights 
w1 = np.random.randn(Di, H1) 
w2 = np.random.randn(H1, Do)

In [76]:
w1

array([[ 1.62434536, -0.61175641, -0.52817175, -1.07296862,  0.86540763,
        -2.3015387 ,  1.74481176, -0.7612069 ,  0.3190391 , -0.24937038],
       [ 1.46210794, -2.06014071, -0.3224172 , -0.38405435,  1.13376944,
        -1.09989127, -0.17242821, -0.87785842,  0.04221375,  0.58281521],
       [-1.10061918,  1.14472371,  0.90159072,  0.50249434,  0.90085595,
        -0.68372786, -0.12289023, -0.93576943, -0.26788808,  0.53035547],
       [-0.69166075, -0.39675353, -0.6871727 , -0.84520564, -0.67124613,
        -0.0126646 , -1.11731035,  0.2344157 ,  1.65980218,  0.74204416]])

In [78]:
w1.shape

(4, 10)

In [80]:
w2

array([[-0.19183555, -0.88762896, -0.74715829],
       [ 1.6924546 ,  0.05080775, -0.63699565],
       [ 0.19091548,  2.10025514,  0.12015895],
       [ 0.61720311,  0.30017032, -0.35224985],
       [-1.1425182 , -0.34934272, -0.20889423],
       [ 0.58662319,  0.83898341,  0.93110208],
       [ 0.28558733,  0.88514116, -0.75439794],
       [ 1.25286816,  0.51292982, -0.29809284],
       [ 0.48851815, -0.07557171,  1.13162939],
       [ 1.51981682,  2.18557541, -1.39649634]])

In [82]:
w2.shape

(10, 3)

A loss function measures how well a machine learning model's predictions match the actual data. It's a way to quantify the error between predicted values (y hat) and true values (y). The goal in training a machine learning model is to minimize this loss.

In [85]:
def Linearloss(yhat, y):
    return(np.square(yhat - y).sum())

The gradient of a loss function is a vector of partial derivatives with respect to the model's parameters. It represents the rate of change of the loss function with respect to each parameter. In simpler terms, the gradient points in the direction in which the loss function increases the most rapidly. The idea is to adjust the model's parameters in the opposite direction of the gradient to minimize the loss function.

In [89]:
def linearLossGrad(y, yhat): 
    return(2*(yhat - y))

A unit activation function is a mathematical function used in neural networks to determine the output of a neuron (also known as a unit) given an input or set of inputs. The activation function applies a transformation to the input signal and helps the network learn complex patterns by introducing non-linearity into the model.

# Workflow
In a neural network, each neuron receives inputs, which are multiplied by the corresponding weights and summed up, along with a bias term. The resulting value is then passed through an activation function to produce the neuron's output.

z=∑ i=1 to n (wi.xi+b)
a=f(z)
where:

wi are the weights,
xi are the input values,
b is the bias term,
z is the weighted sum (also called the linear combination),
f is the activation function,
a is the output of the neuron.

## Types of Activation Functions
1. Sigmoid Function
2. Hyperbolic Tangent
3. Rectified Linear Unit (ReLU)
4. Leaky ReLU
5. Softmax

# We choose the function to be the rectifier linear unit (ReLU).
f (x) = max {0, x}
df/dx = {1 if x > 0 else 0 for x < 0}

In [94]:
def relu(x):
    return(np.maximum(x,0))

def relugrad(x):
    if x < 0:
        return 0
    return 1